name: sites115 # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '2.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: sites115 helps in building websites # 79 char long summary
description: |
  sites115 helps in building websites.

  It provides search functionality for markdown files in a website.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:

parts:
  all-needed-files:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
    - go


apps:
  sites115:
    command: bin/build
